version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_PASSWORD: VfS225Yn225
      MYSQL_ROOT_PASSWORD: VfS225Yn225
      MYSQL_DB: pizzaapp
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql/data

  app:
    build: .
    container_name: java_application
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/pizzaapp
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: VfS225Yn225