version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: pizzaapp
      MYSQL_USER: root
      MYSQL_PASSWORD: ${your_pass}
      MYSQL_ROOT_HOST: localhost
    ports:
      - "3307:3307"
    volumes:
      - ./data:/var/lib/mysql
      - ./PizzaApp/src/main/resources/data.sql:/docker-entrypoint-initdb.d

  app:
    build: .
    container_name: java_application
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/pizzaapp
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${your_pass}
